POST http://localhost:3333/livro
Content-Type: application/json

{
    "titulo": "memorias postumas de bras cubas",
    "autor": "Machado de Assis",
    "npaginas": 400
}

###

GET http://localhost:3333/livros

###

PUT http://localhost:3333/livros/73ce0752-2d55-4b66-8f38-8545107bf9b4
Content-Type: application/json

{
    "titulo": "Duna",
    "autor": "Frank Hebert",
    "npaginas": 631
}

###

PATCH http://localhost:3333/livros/73ce0752-2d55-4b66-8f38-8545107bf9b4
Content-Type: application/json

{
    "npaginas": 1235
}